### ISSUE TITLE
docker-compose example for the documentation available?

### ISSUE THREAD

**Issue by mr-gosh** [Forceu/barcodebuddy-docker#19]
Did anyone built his barcodebuddy setup via docker-compose?
I want to extend my grocy docker-compose file to integrate barcodebuddy - so that would be helpfull but the documentation is really thin atm.

**Comment by mr-gosh** [comment]
I tried it with the following behind a traefik2 proxy but it just creates an ssl error - how did you set this up?

```
---
version: "3.7"
services:
  grocy:
    image: f0rc3/barcodebuddy-docker
    container_name: barcodebuddy
    networks:
      - traefik_proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./config:/config
    #ports:
    #  - 9283:80
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.grocy.rule=Host(`my.sub.domain.de`)"
      - "traefik.http.routers.grocy.tls=true"
      - "traefik.http.routers.grocy.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.grocy.entrypoints=websecure"
      - "traefik.http.services.grocy.loadbalancer.server.port=80"
    restart: unless-stopped


networks:
  traefik_proxy:
    external: true
```
